### ISSUE TITLE
Support multiple seneca api version

### ISSUE THREAD

**Issue by geek** [senecajs/senecajs.org#156]
We need to make the API page version specific.  We can keep it simple and make the landing page have links to the versioned API pages.

**Comment by AdrieanKhisbe** [comment]
What file structure should we go for?

`src/pages/api/index.md` for the current, and `api-X.Y` for the other.

**Comment by geek** [comment]
@AdrieanKhisbe yep, thats what I was thinking.  Like how you split out the contribute pages.  With an index landing page and then child version pages

**Comment by mcdonnelldean** [comment]
Added this to phase one, we should get this done before seneca 2 hits. Documentation should reflect the current version and only split on major version, otherwise we won't be able to reliably support versioning I think.

**Comment by AdrieanKhisbe** [comment]
Well not 100% sure for limiting to only major.
Since we're supposed to add feature on minor function, doc from 1.x should be different from 1.y.

I had one idea in mind, (that might require a metalsmith plugin):
The Api.md is stored on the seneca, on the repo. It is versionned along the code.
The documentation, is just the different versions of this Api.md file.
The metalsmith plugin, would be to include at build time other pages from url. (here: path and tags)

(similar strategy could be applied for the plugins)
(It feels like it's very similar to the strategy done by hapijs documentation)

**Comment by geek** [comment]
I like the idea.  We can add API.md to the seneca repo and then the metalsmith plugin can grab from the latest releases and look in each tree for the file to pull: https://github.com/senecajs/seneca/tree/v1.0.0

**Comment by AdrieanKhisbe** [comment]
exactly! :)

the config in fact is a map ( `path` -> `file`)

**Comment by naomifeehanmoran** [comment]
this is being addressed here https://github.com/senecajs/senecajs.org/issues/156, so closing this.
