### ISSUE TITLE
Spelling! ARG! "separator" 

### ISSUE THREAD

**Issue by rjrodger** [senecajs/senecajs.org#177]
https://github.com/senecajs/senecajs.org/blob/master/src/template/partials/seperator.html

http://i.imgur.com/8mS65Uk.jpg

**Comment by mcdonnelldean** [comment]
@rjrodger In my defence, this came from the theme, I merely copy / pasted it :D

**Comment by AdrieanKhisbe** [comment]
@rjrodger Is that really an Issue? :p

**Comment by orlacoding** [comment]
Yes it's an issue! :) Documentation quality is a core value in Seneca.

**Comment by mcdonnelldean** [comment]
@AdrieanKhisbe A clean house is a happy house :D

**Comment by AdrieanKhisbe** [comment]
@orlacoding, We have so many [real Doc issues](https://github.com/senecajs/senecajs.org/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation) that get no attention, to spoil time for a _detail_ that has no consequence at all for the end user. :wink:

We have to stop with `words` and start to (_seneca_).`act`() :smiley:

**Comment by AdrieanKhisbe** [comment]
@mcdonnelldean, speaking how cleaning, we should do a _grand nettoyage de printemps_ /*sping-cleaning_ ;)

**Comment by orlacoding** [comment]
@AdrieanKhisbe Natural language uses the same principle as code Adrien - details are what make or break quality. It's a core principle of Seneca to have high quality documentation. Quality comprises quality within individual docs files as well as quality in more general terms such as scope and variety.

**Comment by AdrieanKhisbe** [comment]
@orlacoding For sure, and the reverse is also true. code(and so doc) use some language principles

what I would say it what break quality more is not a broken detail in a unexposed area. (what this issue is), but many broken details either in the code (which affect contributors), or in documentation 
_“Stop Wasting Time on the Details and Commit to the Fundamentals”_

Also see my actions on this repo and on the whole seneca ecosystem, You'll see i'm not the kind of person that compromise on quality.
But I'm pragmatic enough to start focusing where we can add the more value, at the least cost.

:smiley:

**Comment by mcdonnelldean** [comment]
Folks, Let's cut this one short.

The bottom line here is nobody is arguing this is an urgent change; just a necessary one. At the end of the day any open issue is something anybody can do. I don't want collaborators getting too zealous over particular wants or needs of the project. Ultimately, any improvement, no matter how minor, is good for the project.

I want new people to see issues like this one and feel they can open similar issues without fear of being questioned as to the validity of the change.

I'm going to do this change myself shortly and close this off now.

**Comment by rjrodger** [comment]
*BDFL Policy*

Documentation quality (incl. structure, grammar, spelling, consistency, etc.) are of equivalent value to Code.

As inspiration: http://www.economist.com/styleguide/introduction

**Comment by mcdonnelldean** [comment]
^ This, quality in everything we do. We are a community project, having tasks available for the community is important, just because an issue is raised does not mean it is going to impact on Collaborator work. Any and all issues relating to quality, no matter how minor, should be raised.

Let's please leave it at this.

**Comment by AdrieanKhisbe** [comment]
we could have like in spacemascs  a `Beginner Friendly` label, 

cf: https://github.com/syl20bnr/spacemacs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Beginner+friendly%22
