### ISSUE TITLE
we're using seneca

### ISSUE THREAD

**Issue by timoweiss** [senecajs/senecajs.org#212]
hey @mcdonnelldean,
a few days ago you ask for a logo for senecajs.org :)

We are a bunch of students of the university of applied science constance.
We rewrote our hapi plugin architecture using seneca to split up our business-logic into services - we really love it! :) 

This is our project page: https://locator-app.com/

I've requested a logo from the designer team and I could send it to you. Or I could create a PR - what ever you prefer :) 

Thanks for the awesome work you guys doing!

PS: I'm going to write my bachelor-thesis about microservices and senecajs (topic is not 100% settled yet :D) in the upcoming months. I'd love to support the project - at least with writing docs/examples :)

**Comment by mcdonnelldean** [comment]
@timoweiss This is really epic!!

If you do decide to write your thesis on it you should at least get on a call with @rjrodger and pick his brain. A lot of thought went into Seneca from a user perspective and it contains a lot of things that will guard you against the reality of big systems. The sort of things that other projects don't hit until something big gets built with them :D

Yeah doc support would be awesome, we are struggling on that front in fairness but I'm not sure how we make it better, people just don't like writing docs.

On the image, whichever you prefer. I can put it up for convenience but because we put the committer in the contributor list we like to let people put their own in if they can manage it. So whatever you're comfortable with. If there is no time just add it to this thread and I can do it.

Your app looks really nice, Kudos to you and your team!

**Comment by timoweiss** [comment]
@mcdonnelldean thanks man, code-structure and pattern might not be that optimal. This was our first attempt working with seneca and microservices in general :dancer: 
Yeah I really like rogers talks and publications.  

I will set up a PR in a sec :D

**Comment by mcdonnelldean** [comment]
It looks awesome! Just working through it myself!

**Comment by mcdonnelldean** [comment]
Going to close this one down 💃
