### ISSUE TITLE
Can Seneca be used with microservices in other platforms? If yes, how?

### ISSUE THREAD

**Issue by kevin-madhu** [senecajs/senecajs.org#227]
Logically, seneca should be usable with other platforms. But I'm not sure because there maybe some implementation detail that'll prevent using it for other platforms. If it's possible to use with other platforms, please make an example project as a part of documentation which is in some other platform.

**Comment by mcdonnelldean** [comment]
@kevin-madhu Seneca supports a number of transports. These carry messages to and from seneca systems, you can use this as an extension point. You can see how we use `CURL` to communicate with a seneca microservice in [nodezoo-github][] via http. In terms of greater implementation you would need to implement [patrun's][] rule set in order to build anything more substantial.

[nodezoo-github]: https://github.com/nodezoo/nodezoo-github
[patrun's]: https://github.com/rjrodger/patrun

**Comment by kevin-madhu** [comment]
Okay Thanks :)

**Comment by kevin-madhu** [comment]
Is it a bad idea to make support for other platforms a part of future plans of the seneca project? Just asking.

**Comment by mcdonnelldean** [comment]
Not at all. We are actually doing some work on the low level api in transport to make it more transparent for non node callers plus some other improvements, see https://github.com/senecajs/seneca/issues/399
