### ISSUE TITLE
guide: how to build a store with seneca-store-test 

### ISSUE THREAD

**Issue by paolochiodi** [senecajs/senecajs.org#72]
Hi, as part of my work in rewriting seneca-store-test I'm going to put together a brief guide on how to build a store.

However, there are a couple of things that are a bit obscure to me, and would be helpful if someone can explain me so that I can add that to the guide.

The first thing I encountered is the ceremony needed to register a store, something like:

``` js
  var meta = seneca.store.init(seneca, opts, store);
  desc = meta.desc;
  seneca.add({ init: store.name, tag: meta.tag }, function (args, done) {
    setup(opts, done);
  });
```

This is common among many of the current stores, but I'm not sure why is `seneca.store.init` needed and what it actually does, what is the meta object returned, and what's the need for the "init command" registered into seneca.

I'm also wondering if we are open to change and simplify this part of the api.

cc @mcdonnelldean @geek @rjrodger 

[Trello Card](https://trello.com/c/PhQ1cZBd/59-senecajs-org-guide-how-to-build-a-store-with-seneca-store-test)

**Comment by paolochiodi** [comment]
reposted from https://github.com/rjrodger/seneca/issues/186#issuecomment-147769307

**Comment by mcdonnelldean** [comment]
Awesome also, I want to make sure we capture the Yeoman generator @geek build for same.

**Comment by mcdonnelldean** [comment]
@paolochiodi Answers for the above.

The init stuff is basically a hook to allow a plugin to run a setup. Generally a plugin will have,

```js
seneca.add({init: 'plugin name', tag: 'instance tag'}, ...)
```
declared so that when seneca inits the store it will get called. It provides essentially an 'onload' event.

The meta stuff is just a bunch of data that seneca generates when you give it your plugin. Things like tags, log description, etc. Basically metadata about your plugin.
